version: '3'

services:
  rdbms:
    image: mysql:latest
    volumes:
      - ./db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sejongcocoding
      - MYSQL_DATABASE=sejong_openapi
    ports:
      - 3306:3306