logging:
  level:
    com:
      querydsl:
        sql: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8080
  tomcat:
    max-http-form-post-size: 10MB
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true
      force-request: true
      enabled: true

spring:
  profiles:
    active: default # local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://127.0.0.1:3306/sejong_openapi?serverTimezone=Asia/Seoul&charset=UTF-8'
    username: root
    password: sejongcocoding
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: me.cocoding.openapi.component.custommysqldialect.CustomMySqlDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false

  thymeleaf:
    mode: HTML

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: b2b1d4932c9d35
    password: 4f807c9ccc592c
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
        mime:
          charset: UTF-8

  flyway:
    baseline-version: 0
    out-of-order: true